services:
  whatsapp:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: "on-failure"
    ports:
      - "3081:3081"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --webhook="https://workflow.traigalo.online/webhook-test/32c9cb9b-760d-4e06-be90-63909c11cccf"
      - --basic-auth=${WA_USER}:${WA_PASSWORD}
      - --port=3081
      - --debug=false
      - --os=Chrome
      - --account-validation=false

volumes:
  whatsapp: